name: Lint

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9
      with:
        version: v2.6.1
        skip-cache: true
