name: Lint

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
      with:
        version: v2.12.2
        skip-cache: true
