name: Lint

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@0adbc47a5910e47adb692df88187ec8c73c76778 # v6
      with:
        version: v1.64.5
        skip-cache: true
