name: Lint

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
      with:
        version: v2.12.2
        skip-cache: true
