name: Lint

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea # v6
      with:
        version: v1.64.7
        skip-cache: true
