name: Lint

runs:
  using: composite
  steps:
    - name: Lint
      uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6
      with:
        version: v1.63.4
        skip-cache: true
