defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:3348c5f7b97a4d63944034a8c6c43ad8bc69771b2564bed32ea3173bc96b4e04

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
