defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:9047a7c9e2d7dbc6614053e82c859e0c409591ccf054447fdc375a5e5741f70b

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
