defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:beb6a9eaf915a03a6fedbeda117fd327cd6b08883ae5fa58bd2ac7c0980318cd

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
