defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:797e62f43d04d792e9f930913e7d9f5a63e92bd19ca5e7e5139a692decee2dbc

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
