defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:561b669256bd2b5a8afed34614e8cb1b98e4e2f66d42ac7a8d80d317d8c8688a

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
