defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:092aad9f6448695b6e20333a8faa93fe3637bcf4e88aa804b8f01545eaf288bd

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
