defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:d7518504f59dacbc90852349c0878871199cefd4bed7952d2eeb7cc3ddbe69e5

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
