defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:e78eb21f59f52446a23f7d45e78805c4f26406a6e9c4b21ec50dfdf07e6bec57

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
