defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:0f33d0da1c868b246fffb2b951754689bdb5de60771157ed0a6a149a9be856f6

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
