defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:d2a76860057c1260ea5dc8ae4e18beff5ccfb1b67004295c9ab6951833e93de7

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
