defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:d94c01c30dda455626c9642272b489adfc402982b99849149ca678ff4d45b267

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
