defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:d6a97eb401cbc7c6d48be76ad81d7899b94303580859d396b52b67bc84ea7345

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
