defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:633aabd19a2d1b9d4ccc1f4b704eb5e9d34ce6ad231a4f5b7f7a3af1307fdba8

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
