defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:01f45a2a6b87a54e242361c217335b4e792b09b92cd4b0780f8b253e27d299bb

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
