defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:2a625816afa718bedc374daaed98b7171bb74591f10067f42efb448bfc8ea1ee

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
