defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:93b70336be10c325d5a96016971b71b38d8e79e5148af2144f2aae93ee9367c3

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
