defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:a1f8a15835e5efebb41f7a3a1a81d32143c7c0ac83a27d85401fe52904c90182

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
