defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:bde549df44d5158013856a778b34d8972cf52bb2038ec886475d857ec7c365ed

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
