defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:68b8855b2ce85b1c649c0e6c69f93c214f4db75359e4fd07b1df951a4e2b0140

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
