defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:e55a04f85f58e6b0e36bae05b8ff18c79035e65c0151e4e866eb49679782d28e

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
