defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:d786d1c686ce4a49376cd2f068d91e691b2bb2e3a6f38513b2396b69b1a9c06f

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
