defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:5e9c88174a28c259c349f308dd661a6ec61ed5f8c72ecfaefb46cceb811b55a1

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
