defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:48278935856fba0e9fac80365ae9a5b33297f7e5682c2dcb86ecfe5eb6878972

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
