defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:207a5673ab31ed83332e54ae33d0f1de4adb5984bd93b8309789889e7bf30ba6

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
