defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:11ec91f0372630a2ca3764cea6325bebb0189a514084463cbb3724e5bb350d14

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
