defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:99a5f826e71115aef9f63368120a6aa518323e052297718e9bf084fb84def93c

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
