defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:24dd7ff8788fdfadda39eeeaefefb6d1cec6002a545935a5f7e017484053734f

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
