defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:7124bf9a6f70e0750d14ef16f1791f322f6d62f50a49223a709f7ed41644c353

builds:
  - id: default
    flags:
      - -trimpath
    ldflags:
      - -s -w
