name: mta-sts-exporter-examples

volumes:
  mta-sts-reports: {}

configs:
  mta-sts-exporter:
    # all default values, your config may only contain values you want to override
    content: |
      port: 8080

      log:
        json: true

      policy:
        enabled: true
        path: /.well-known/mta-sts.txt
        version: STSv1
        mode: enforce
        mx:
          - example.com
        maxage: 86400

      reports:
        enabled: true
        path: /report
        max:
          body: 1048576
          json: 5242880
        save:
          enabled: true
          path: /tmp/reports

      metrics:
        enabled: true
        port: 8081
        path: /metrics
        go: false

x-service: &service
  restart: unless-stopped
  logging:
    driver: journald
    options:
      tag: "{{.Name}}/{{.ID}}"

x-healthcheck: &healthcheck
  start_period: 15s
  start_interval: 1s
  interval: 15s
  timeout: 3s
  retries: 3

services:
  mta-sts-exporter:
    <<: *service
    image: phiag/mta-sts-exporter:1.4.1@sha256:874a452d5d5ed06c0623509d179a2a548abdc15cb499575bd5c5d7aee2394346
    # only required for rootless docker to write to volume
    user: 0:0
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
      - "[::1]:8080:8080"
      - "[::1]:8081:8081"
    healthcheck:
      <<: *healthcheck
      test: [CMD, /ko-app/mta-sts-exporter, -health]
    environment:
      CONFIG_PATH: /mta-sts-exporter
    configs:
      - mta-sts-exporter
    volumes:
      - mta-sts-reports:/tmp/reports

  mta-sts-exporter-env:
    <<: *service
    image: phiag/mta-sts-exporter:1.4.1@sha256:874a452d5d5ed06c0623509d179a2a548abdc15cb499575bd5c5d7aee2394346
    expose:
      - 8080
      - 8081
    healthcheck:
      <<: *healthcheck
      test: [CMD, /ko-app/mta-sts-exporter, -health]
    environment:
      PORT: 8080
      LOG_JSON: true
      POLICY_ENABLED: true
      POLICY_PATH: /.well-known/mta-sts.txt
      POLICY_VERSION: STSv1
      POLICY_MODE: enforce
      POLICY_MX: example.com,mx.example.com
      POLICY_MAXAGE: 86400
      REPORTS_ENABLED: true
      REPORTS_PATH: /report
      REPORTS_MAX_BODY: 1048576
      REPORTS_MAX_JSON: 5242880
      REPORTS_SAVE_ENABLED: true
      REPORTS_SAVE_PATH: /tmp/reports
      METRICS_ENABLED: true
      METRICS_PORT: 8081
      METRICS_PATH: /metrics
      METRICS_GO: false

  mta-sts-exporter-traefik:
    <<: *service
    image: phiag/mta-sts-exporter:1.4.1@sha256:874a452d5d5ed06c0623509d179a2a548abdc15cb499575bd5c5d7aee2394346
    expose:
      - 8080
      - 8081
    healthcheck:
      <<: *healthcheck
      test: [CMD, /ko-app/mta-sts-exporter, -health]
    environment:
      POLICY_MX: mx1.example.com,mx2.example.com
    labels:
      traefik.enable: true
      traefik.http.routers.mta_sts.rule: Host(`mta-sts.example.com`)
      traefik.http.routers.mta_sts.entrypoints: https
      traefik.http.routers.mta_sts.tls: true
      traefik.http.routers.mta_sts.tls.certresolver: letsencrypt
