name: mta-sts-exporter-example

configs:
  mta-sts-exporter:
    content: |
      port: 8080

      log:
        json: true

      policy:
        enabled: true
        path: /.well-known/mta-sts.txt
        version: STSv1
        mode: enforce
        mx:
          - example.com
        maxage: 86400

      reports:
        path: /report
        maxbodysize: 1048576
        maxjsonsize: 5242880
        save: true
        savepath: /tmp/reports

      metrics:
        port: 8081
        path: /metrics
        go: false

volumes:
  mta-sts-reports: {}

x-service: &service
  restart: unless-stopped
  logging:
    driver: journald
    options:
      tag: "{{.Name}}/{{.ID}}"

x-healthcheck: &healthcheck
  start_period: 15s
  start_interval: 1s
  interval: 15s
  timeout: 3s
  retries: 3

services:
  mta-sts-exporter:
    <<: *service
    image: phiag/mta-sts-exporter:latest
    # allow rootless docker to write to volume
    user: 0:0
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
      - "[::1]:8080:8080"
      - "[::1]:8081:8081"
    healthcheck:
      <<: *healthcheck
      test: [CMD, /ko-app/mta-sts-exporter, -health]
    environment:
      CONFIG_PATH: /mta-sts-exporter
    configs:
      - mta-sts-exporter
    volumes:
      - mta-sts-reports:/tmp/reports
